-- create tables

create table d11_ruolo (
    id                number generated by default on null as identity
                      constraint d11_ruolo_id_pk primary key,
    ruolo             varchar2(20 char)
                      constraint d11_ruolo_ruolo_unq unique not null,
    tariffa_oraria    number not null
);



create table d11_persona (
    id          number generated by default on null as identity
                constraint d11_persona_id_pk primary key,
    ruolo_id    number
                constraint d11_persona_ruolo_id_fk
                references d11_ruolo not null,
    nome        varchar2(30 char)
                constraint d11_persona_nome_unq unique not null
);

-- table index
create index d11_persona_i1 on d11_persona (ruolo_id);



create table d11_cliente (
    id         number generated by default on null as identity
               constraint d11_cliente_id_pk primary key,
    cliente    varchar2(30 char)
               constraint d11_cliente_cliente_unq unique not null
);



create table d11_progetto (
    id            number generated by default on null as identity
                  constraint d11_progetto_id_pk primary key,
    cliente_id    number
                  constraint d11_progetto_cliente_id_fk
                  references d11_cliente not null,
    progetto      varchar2(30 char)
                  constraint d11_progetto_progetto_unq unique not null
);

-- table index
create index d11_progetto_i1 on d11_progetto (cliente_id);



create table d11_commessa (
    id                      number generated by default on null as identity
                            constraint d11_commessa_id_pk primary key,
    progetto_id             number
                            constraint d11_commessa_progetto_id_fk
                            references d11_progetto not null,
    codice_commessa         varchar2(30 char)
                            constraint d11_commessa_codice_commessa_unq unique not null,
    descrizione_commessa    varchar2(50 char) not null
);

-- table index
create index d11_commessa_i1 on d11_commessa (progetto_id);



create table d11_ore (
    id             number generated by default on null as identity
                   constraint d11_ore_id_pk primary key,
    persona_id     number
                   constraint d11_ore_persona_id_fk
                   references d11_persona not null,
    commessa_id    number
                   constraint d11_ore_commessa_id_fk
                   references d11_commessa not null,
    data           date not null,
    ore            number not null,
    costo          number not null
);

-- table index
create index d11_ore_i1 on d11_ore (persona_id);

create index d11_ore_i2 on d11_ore (commessa_id);



-- Generated by Quick SQL undefined 14/4/2024, 13:21:08

/*
ruolo
  ruolo vc20 /nn /unique
  tariffa_oraria num /nn

persona
  nome vc30 /nn /unique
  ruolo id num /nn

cliente
  cliente vc30 /nn /unique
  
progetto
  progetto vc30 /nn /unique
  cliente id num /nn

commessa
  codice_commessa vc30 /nn /unique
  descrizione_commessa vc50 /nn
  progetto id num /nn

ore
  persona id num /nn
  commessa id num /nn
  data date /nn
  ore num /nn
  costo num /nn




 Non-default options:
# settings = {"apex":"Y","db":"19c","prefix":"d11"}

*/