-- create tables

create table d24_persona (
    id      number generated by default on null as identity
            constraint d24_persona_id_pk primary key,
    nome    varchar2(30 char) not null,
    data    date not null
);



-- Generated by Quick SQL 1.2.9 08/07/2024, 11:56:27

/*
persona 
  nome vc30 /nn
  data d /nn




 Non-default options:
# settings = {"apex":"Y","db":"19c","prefix":"d24","pk":"IDENTITY"}

*/