-- create tables

create table d23_approvazione (
    id         number generated by default on null as identity
               constraint d23_approvazione_id_pk primary key,
    nome       varchar2(255 char) not null,
    email      varchar2(255 char) not null,
    livello    number default on null 1 not null
);

alter table d23_approvazione add constraint d23_approvazione_uk unique (nome);



create table d23_richiesta (
    id                   number generated by default on null as identity
                         constraint d23_richiesta_id_pk primary key,
    richiedente          varchar2(50 char) not null,
    email_richiedente    varchar2(50 char) not null,
    importo              number not null,
    descrizione          varchar2(255 char) not null
);



-- Generated by Quick SQL 1.2.9 05/07/2024, 09:25:13

/*
approvazione /unique nome 
  nome vc255 /nn
  email vc255 /nn
  livello num /nn /default 1

richiesta 
  richiedente vc50 /nn 
  email_richiedente vc50 /nn 
  importo num /nn
  descrizione vc255 /nn




 Non-default options:
# settings = {"apex":"Y","db":"19c","prefix":"d23","pk":"IDENTITY"}

*/