-- create tables

create table cliente (
    id             number generated by default on null as identity
                   constraint cliente_id_pk primary key,
    cod_cliente    varchar2(30 char) not null,
    cliente        varchar2(100 char) not null
);

alter table cliente add constraint cliente_uk unique (cod_cliente);



create table stato (
    id           number generated by default on null as identity
                 constraint stato_id_pk primary key,
    cod_stato    varchar2(30 char) not null,
    stato        varchar2(100 char) not null
);

alter table stato add constraint stato_uk unique (cod_stato);



create table attivita (
    id                        number generated by default on null as identity
                              constraint attivita_id_pk primary key,
    stato_id                  number                              constraint attivita_stato_id_fk
                              references stato not null,
    cliente_id                number                              constraint attivita_cliente_id_fk
                              references cliente not null,
    cod_attivita              varchar2(30 char) not null,
    attivita                  varchar2(100 char) not null,
    perc_completamento        integer not null,
    data_scadenza_prevista    date not null,
    data_chiusura             date
);

-- table index
create index attivita_i1 on attivita (stato_id);

create index attivita_i2 on attivita (cliente_id);

alter table attivita add constraint attivita_uk unique (cod_attivita);



create table persona (
    id             number generated by default on null as identity
                   constraint persona_id_pk primary key,
    cod_persona    varchar2(30 char) not null,
    persona        varchar2(100 char) not null,
    email          varchar2(100 char) not null
);

alter table persona add constraint persona_uk unique (cod_persona);



create table tariffa (
    id             number generated by default on null as identity
                   constraint tariffa_id_pk primary key,
    cod_tariffa    varchar2(30 char) not null,
    tariffa        varchar2(100 char) not null,
    valore         number not null
);

alter table tariffa add constraint tariffa_uk unique (cod_tariffa);



create table persona_tariffa (
    id             number generated by default on null as identity
                   constraint persona_tariffa_id_pk primary key,
    persona_id     number                   constraint persona_tariffa_persona_id_fk
                   references persona on delete cascade not null,
    tariffa_id     number                   constraint persona_tariffa_tariffa_id_fk
                   references tariffa on delete cascade not null,
    data_inizio    date not null,
    data_fine      date
);

-- table index
create index persona_tariffa_i1 on persona_tariffa (persona_id);

create index persona_tariffa_i2 on persona_tariffa (tariffa_id);

alter table persona_tariffa add constraint persona_tariffa_uk unique (persona_id,data_fine);



create table tipo (
    id          number generated by default on null as identity
                constraint tipo_id_pk primary key,
    cod_tipo    varchar2(30 char) not null,
    tipo        varchar2(100 char) not null
);

alter table tipo add constraint tipo_uk unique (cod_tipo);



create table ore (
    id             number generated by default on null as identity
                   constraint ore_id_pk primary key,
    persona_id     number                   constraint ore_persona_id_fk
                   references persona on delete cascade not null,
    attivita_id    number                   constraint ore_attivita_id_fk
                   references attivita on delete cascade not null,
    tipo_id        number                   constraint ore_tipo_id_fk
                   references tipo not null,
    data           date not null,
    ore            number not null
);

-- table index
create index ore_i1 on ore (persona_id);

create index ore_i2 on ore (attivita_id);

create index ore_i3 on ore (tipo_id);

alter table ore add constraint ore_uk unique (persona_id,attivita_id,tipo_id,data);



-- Generated by Quick SQL 1.2.9 22/07/2024, 14:50:14

/*
cliente /unique cod_cliente
  cod_cliente vc30 /nn
  cliente vc100 /nn

stato /unique cod_stato
  cod_stato vc30 /nn
  stato vc100 /nn

attivita /unique cod_attivita
  cod_attivita vc30 /nn
  attivita vc100 /nn
  perc_completamento int /nn
  data_scadenza_prevista d /nn
  data_chiusura d
  stato id /nn
  cliente id /nn

persona /unique cod_persona
  cod_persona vc30 /nn
  persona vc100 /nn
  email vc100 /nn

tariffa /unique cod_tariffa
  cod_tariffa vc30 /nn
  tariffa vc100 /nn
  valore num /nn  

persona_tariffa /unique persona_id,data_fine
  persona id /nn /cascade
  tariffa id /nn /cascade
  data_inizio d /nn
  data_fine  d

tipo /unique cod_tipo
  cod_tipo vc30 /nn
  tipo vc100 /nn

ore /unique persona_id,attivita_id,tipo_id,data
  persona id /nn /cascade
  attivita id /nn /cascade
  tipo id /nn
  data d /nn
  ore num /nn

 Non-default options:
# settings = {"apex":"Y","db":"19c","pk":"IDENTITY"}

*/
