drop table d28_cliente cascade constraints;
drop table d28_stato cascade constraints;
drop table d28_attivita cascade constraints;
drop table d28_persona cascade constraints;
drop table d28_tariffa cascade constraints;
drop table d28_persona_tariffa cascade constraints;
drop table d28_tipo cascade constraints;
drop table d28_ore cascade constraints;
-- create tables

create table d28_cliente (
    id             number generated by default on null as identity
                   constraint d28_cliente_id_pk primary key,
    cod_cliente    varchar2(30 char) not null,
    cliente        varchar2(100 char) not null,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

alter table d28_cliente add constraint d28_cliente_uk unique (cod_cliente);



create table d28_stato (
    id            number generated by default on null as identity
                  constraint d28_stato_id_pk primary key,
    cod_stato     varchar2(30 char) not null,
    stato         varchar2(100 char) not null,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);

alter table d28_stato add constraint d28_stato_uk unique (cod_stato);



create table d28_attivita (
    id                        number generated by default on null as identity
                              constraint d28_attivita_id_pk primary key,
    stato_id                  number                              constraint d28_attivita_stato_id_fk
                              references d28_stato not null,
    cliente_id                number                              constraint d28_attivita_cliente_id_fk
                              references d28_cliente not null,
    cod_attivita              varchar2(30 char) not null,
    attivita                  varchar2(100 char) not null,
    perc_completamento        integer not null,
    data_scadenza_prevista    date not null,
    data_chiusura             date not null,
    created                   date not null,
    created_by                varchar2(255 char) not null,
    updated                   date not null,
    updated_by                varchar2(255 char) not null
);

-- table index
create index d28_attivita_i1 on d28_attivita (stato_id);

create index d28_attivita_i2 on d28_attivita (cliente_id);

alter table d28_attivita add constraint d28_attivita_uk unique (cod_attivita);



create table d28_persona (
    id             number generated by default on null as identity
                   constraint d28_persona_id_pk primary key,
    cod_persona    varchar2(30 char) not null,
    persona        varchar2(100 char) not null,
    email          varchar2(100 char) not null,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

alter table d28_persona add constraint d28_persona_uk unique (cod_persona);



create table d28_tariffa (
    id             number generated by default on null as identity
                   constraint d28_tariffa_id_pk primary key,
    cod_tariffa    varchar2(30 char) not null,
    tariffa        varchar2(100 char) not null,
    valore         number not null,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

alter table d28_tariffa add constraint d28_tariffa_uk unique (cod_tariffa);



create table d28_persona_tariffa (
    id             number generated by default on null as identity
                   constraint d28_persona_tariffa_id_pk primary key,
    persona_id     number                   constraint d28_persona_tariffa_persona_id_fk
                   references d28_persona on delete cascade not null,
    tariffa_id     number                   constraint d28_persona_tariffa_tariffa_id_fk
                   references d28_tariffa on delete cascade not null,
    data_inizio    date not null,
    data_fine      date,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

-- table index
create index d28_persona_tariffa_i1 on d28_persona_tariffa (persona_id);

create index d28_persona_tariffa_i2 on d28_persona_tariffa (tariffa_id);

alter table d28_persona_tariffa add constraint d28_persona_tariffa_uk unique (persona_id,data_fine);



create table d28_tipo (
    id            number generated by default on null as identity
                  constraint d28_tipo_id_pk primary key,
    cod_tipo      varchar2(30 char) not null,
    tipo          varchar2(100 char) not null,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);

alter table d28_tipo add constraint d28_tipo_uk unique (cod_tipo);



create table d28_ore (
    id             number generated by default on null as identity
                   constraint d28_ore_id_pk primary key,
    persona_id     number                   constraint d28_ore_persona_id_fk
                   references d28_persona on delete cascade not null,
    attivita_id    number                   constraint d28_ore_attivita_id_fk
                   references d28_attivita on delete cascade not null,
    tipo_id        number                   constraint d28_ore_tipo_id_fk
                   references d28_tipo not null,
    data           date not null,
    ore            number not null,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);

-- table index
create index d28_ore_i1 on d28_ore (persona_id);

create index d28_ore_i2 on d28_ore (attivita_id);

create index d28_ore_i3 on d28_ore (tipo_id);

alter table d28_ore add constraint d28_ore_uk unique (persona_id,attivita_id,data);



-- triggers
create or replace trigger d28_cliente_biu
    before insert or update
    on d28_cliente
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_cliente_biu;
/


create or replace trigger d28_stato_biu
    before insert or update
    on d28_stato
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_stato_biu;
/


create or replace trigger d28_attivita_biu
    before insert or update
    on d28_attivita
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_attivita_biu;
/


create or replace trigger d28_persona_biu
    before insert or update
    on d28_persona
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_persona_biu;
/


create or replace trigger d28_tariffa_biu
    before insert or update
    on d28_tariffa
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_tariffa_biu;
/


create or replace trigger d28_persona_tariffa_biu
    before insert or update
    on d28_persona_tariffa
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_persona_tariffa_biu;
/


create or replace trigger d28_tipo_biu
    before insert or update
    on d28_tipo
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_tipo_biu;
/


create or replace trigger d28_ore_biu
    before insert or update
    on d28_ore
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d28_ore_biu;
/


-- Generated by Quick SQL 1.2.9 21/07/2024, 17:38:56

/*
cliente /unique cod_cliente
  cod_cliente vc30 /nn
  cliente vc100 /nn

stato /unique cod_stato
  cod_stato vc30 /nn
  stato vc100 /nn

attivita /unique cod_attivita
  cod_attivita vc30 /nn
  attivita vc100 /nn
  perc_completamento int /nn
  data_scadenza_prevista d /nn
  data_chiusura d /nn
  stato id /nn
  cliente id /nn


persona /unique cod_persona
  cod_persona vc30 /nn
  persona vc100 /nn
  email vc100 /nn

tariffa /unique cod_tariffa
  cod_tariffa vc30 /nn
  tariffa vc100 /nn
  valore num /nn

persona_tariffa /unique persona_id,data_fine
  persona id /nn /cascade
  tariffa id /nn /cascade
  data_inizio d /nn
  data_fine  d

tipo /unique cod_tipo
  cod_tipo vc30 /nn
  tipo vc100 /nn

ore /unique persona_id,attivita_id,data
  persona id /nn /cascade
  attivita id /nn /cascade
  tipo id /nn
  data d /nn
  ore num /nn




 Non-default options:
# settings = {"apex":"Y","auditcols":true,"db":"19c","drop":true,"prefix":"d28","pk":"IDENTITY"}

*/
