-- create tables

create table d08_marchio (
    id         number generated by default on null as identity
               constraint d08_marchio_id_pk primary key,
    marchio    varchar2(20 char)
               constraint marchio_marchio_unq unique not null
);



create table d08_prodotto (
    id               number generated by default on null as identity
                     constraint d08_prodotto_id_pk primary key,
    marchio_id       number
                     constraint d08_prodotto_marchio_id_fk
                     references d08_marchio not null,
    prodotto_cod     varchar2(255 char) not null,
    prodotto         varchar2(255 char) not null,
    descrizione      varchar2(1500 char),
    prezzo           number,
    tags             varchar2(400 char),
    genere           varchar2(20 char),
    data_rilascio    date,
    url_immagine     varchar2(400 char)
);

-- table index
create index d08_prodotto_i1 on d08_prodotto (marchio_id);



-- Generated by Quick SQL undefined 22/3/2024, 12:46:47

/*
marchio
  marchio vc20 /nn /unique

prodotto
  marchio id /nn
  prodotto_cod vc255 /nn
  prodotto vc255 /nn
  descrizione vc1500
  prezzo num
  tags vc400
  genere vc20
  data_rilascio d
  url_immagine vc400

 


 Non-default options:
# settings = {"apex":"Y","db":"19c","prefix":"d08"}

*/