drop table d08_tipo_prodotto cascade constraints;
drop table d08_prodotto cascade constraints;
drop table d08_cliente cascade constraints;
drop table d08_fornitore cascade constraints;
drop table d08_acquisto cascade constraints;
drop table d08_vendita cascade constraints;
-- create tables

create table d08_tipo_prodotto (
    id               number generated by default on null as identity
                     constraint d08_tipo_prodotto_id_pk primary key,
    tipo_prodotto    varchar2(50 char)
                     constraint tipo_prodotto_tipo_prodotto_unq unique not null,
    gruppo           varchar2(50 char) not null
);



create table d08_prodotto (
    id                  number generated by default on null as identity
                        constraint d08_prodotto_id_pk primary key,
    tipo_prodotto_id    number
                        constraint d08_prodotto_tipo_prodotto_id_fk
                        references d08_tipo_prodotto not null,
    prodotto            varchar2(50 char)
                        constraint prodotto_prodotto_unq unique not null,
    prezzo_acquisto     number not null,
    prezzo_vendita      number not null
);

-- table index
create index d08_prodotto_i1 on d08_prodotto (tipo_prodotto_id);



create table d08_cliente (
    id         number generated by default on null as identity
               constraint d08_cliente_id_pk primary key,
    cliente    varchar2(50 char)
               constraint cliente_cliente_unq unique not null,
    zona       varchar2(10 char) not null
);



create table d08_fornitore (
    id           number generated by default on null as identity
                 constraint d08_fornitore_id_pk primary key,
    fornitore    varchar2(50 char)
                 constraint fornitore_fornitore_unq unique not null,
    zona         varchar2(50 char) not null
);



create table d08_acquisto (
    id              number generated by default on null as identity
                    constraint d08_acquisto_id_pk primary key,
    fornitore_id    number
                    constraint d08_acquisto_fornitore_id_fk
                    references d08_fornitore not null,
    prodotto_id     number
                    constraint d08_acquisto_prodotto_id_fk
                    references d08_prodotto not null,
    data            date not null,
    quantita        number not null
);

-- table index
create index d08_acquisto_i1 on d08_acquisto (fornitore_id);

create index d08_acquisto_i2 on d08_acquisto (prodotto_id);



create table d08_vendita (
    id             number generated by default on null as identity
                   constraint d08_vendita_id_pk primary key,
    cliente_id     number
                   constraint d08_vendita_cliente_id_fk
                   references d08_cliente not null,
    prodotto_id    number
                   constraint d08_vendita_prodotto_id_fk
                   references d08_prodotto not null,
    data           date not null,
    quantita       number not null
);

-- table index
create index d08_vendita_i1 on d08_vendita (cliente_id);

create index d08_vendita_i2 on d08_vendita (prodotto_id);



-- Generated by Quick SQL undefined 22/3/2024, 15:02:41

/*
tipo_prodotto
  tipo_prodotto vc50 /nn /unique
  gruppo vc50 /nn

prodotto
  prodotto vc50 /nn /unique
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto id /nn

cliente
  cliente vc50 /nn /unique
  zona vc10 /nn

fornitore
  fornitore vc50 /nn /unique
  zona vc50 /nn

acquisto
  data date /nn
  fornitore id /nn
  prodotto id /nn
  quantita num /nn

vendita
  data date /nn
  cliente id  /nn
  prodotto id /nn
  quantita num /nn




 Non-default options:
# settings = {"apex":"Y","db":"19c","drop":true,"prefix":"D08"}

*/
