-- inserisce valori manualmente ( NON INSERIRE lo facciamo dopo)
insert into d08_marchio (id,marchio) values (1,'CORE/NEO');


-- inserisce valori da select non serve la parola VALUES
-- ( NON INSERIRE lo facciamo dopo)
insert into d08_marchio (id,marchio) select id,marchio from d05_marchio;


-- quando ometto i campi tra parentesi significa che li fornisco tutti 
-- rispettando l'ordine delle colonne ( ora si può inserire!! )
insert into d08_marchio select * from d05_marchio;

insert into d08_prodotto select * from d05_prodotto;




-- il massimo id è 7
select max(id) from d08_marchio;

alter table d08_marchio
modify id generated by default on null as identity restart start with 8;

-- il massimo id è  29
select max(id) from d08_prodotto;

alter table d08_prodotto
modify id generated by default on null  as identity restart start with 30;