-- create tables

create table d25_utente (
    id           number generated by default on null as identity
                 constraint d25_utente_id_pk primary key,
    utente       varchar2(30 char) not null,
    email        varchar2(255 char),
    attivo_yn    varchar2(1 char) default on null 'Y' not null
                 constraint d25_utente_attivo_yn check (attivo_yn in ('Y','N'))
);

alter table d25_utente add constraint d25_utente_uk unique (utente);



create table d25_log (
    id      number generated by default on null as identity
            constraint d25_log_id_pk primary key,
    log     varchar2(50 char) not null,
    data    date not null
);



-- Generated by Quick SQL 1.2.9 12/07/2024, 13:59:21

/*
utente /unique utente
  utente vc30 /nn 
  email
  attivo_yn /nn /default Y

log
  log vc50 /nn
  data d /nn



 Non-default options:
# settings = {"apex":true,"db":"19c","prefix":"d25","pk":"IDENTITY"}

*/