-- create tables

create table d12_cliente (
    id                 number generated by default on null as identity
                       constraint d12_cliente_id_pk primary key,
    codice_cliente     varchar2(20 char) not null,
    ragione_sociale    varchar2(50 char) not null,
    piva               varchar2(11 char) not null,
    indirizzo          varchar2(100 char) not null,
    codice_sdi         varchar2(6 char)
);



create table d12_fattura_testata (
    id             number generated by default on null as identity
                   constraint d12_fattura_testata_id_pk primary key,
    cliente_id     number
                   constraint d12_fattura_testata_cliente_id_fk
                   references d12_cliente not null,
    anno           integer not null,
    numero         integer not null,
    descrizione    varchar2(50 char) not null,
    data           date not null
);

-- table index
create index d12_fattura_testata_i1 on d12_fattura_testata (cliente_id);



create table d12_fattura_dettaglio (
    id                    number generated by default on null as identity
                          constraint d12_fattura_dettaglio_id_pk primary key,
    fattura_testata_id    number
                          constraint d12_fattura_dettaglio_fattura_testata_id_fk
                          references d12_fattura_testata not null,
    riga                  number not null,
    descrizione           varchar2(100 char) not null,
    quantita              number not null,
    importo               number not null
);

-- table index
create index d12_fattura_dettaglio_i1 on d12_fattura_dettaglio (fattura_testata_id);



-- Generated by Quick SQL undefined 19/4/2024, 12:34:45

/*
cliente
  codice_cliente vc20 /nn
  ragione_sociale vc50 /nn
  piva vc11 /nn
  indirizzo vc100 /nn
  codice_sdi vc6 

fattura_testata
  anno int /nn
  numero int /nn 
  descrizione vc50 /nn
  data date /nn
  cliente id /nn

fattura_dettaglio
  fattura_testata id /nn
  riga num /nn
  descrizione vc100 /nn
  quantita num /nn
  importo num /nn
  

# settings = {"apex":"Y","db":"19c","prefix":"d12"}

*/