-- create tables

create table d19_persona (
    id            number generated by default on null as identity
                  constraint d19_persona_id_pk primary key,
    nome          varchar2(50 char)
                  constraint d19_persona_nome_unq unique not null,
    eta           number,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);



-- triggers
create or replace trigger d19_persona_biu
    before insert or update
    on d19_persona
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end d19_persona_biu;
/


-- Generated by Quick SQL 1.2.9 24/5/2024, 12:57:01

/*
persona
  nome vc50 /nn /unique
  eta num



 Non-default options:
# settings = {"apex":"Y","auditcols":true,"db":"19c","prefix":"d19","pk":"IDENTITY"}

*/