-- drop objects
drop table d19_marca cascade constraints;
drop table d19_automezzo cascade constraints;
drop table d19_tipo_carburante cascade constraints;
drop table d19_rifornimento cascade constraints;
drop table d19_manutenzione cascade constraints;

-- create tables
create table d19_marca (
    id                             number generated by default on null as identity 
                                   constraint d19_marca_id_pk primary key,
    marca                          varchar2(8 char)
                                   constraint d19_marca_marca_unq unique not null
)
;

create table d19_automezzo (
    id                             number generated by default on null as identity 
                                   constraint d19_automezzo_id_pk primary key,
    marca_id                       number
                                   constraint d19_automezzo_marca_id_fk
                                   references d19_marca not null,
    targa                          varchar2(10 char)
                                   constraint d19_automezzo_targa_unq unique not null,
    modello                        varchar2(30 char) not null
)
;

-- table index
create index d19_automezzo_i1 on d19_automezzo (marca_id);

create table d19_tipo_carburante (
    id                             number generated by default on null as identity 
                                   constraint d19_tipo_carburan_id_pk primary key,
    tipo_carburante                varchar2(7 char)
                                   constraint d19_tipo_car_tipo_carbura_unq unique not null
)
;

create table d19_rifornimento (
    id                             number generated by default on null as identity 
                                   constraint d19_rifornimento_id_pk primary key,
    automezzo_id                   number
                                   constraint d19_rifornimen_automezzo_i_fk
                                   references d19_automezzo not null,
    tipo_carburante_id             number
                                   constraint d19_rifornim_tipo_carburan_fk
                                   references d19_tipo_carburante not null,
    data_rifornimento              date not null,
    quantita                       number not null,
    importo                        number not null
)
;

-- table index
create index d19_rifornimento_i1 on d19_rifornimento (automezzo_id);
create index d19_rifornimento_i122 on d19_rifornimento (tipo_carburante_id);

create table d19_manutenzione (
    id                             number generated by default on null as identity 
                                   constraint d19_manutenzione_id_pk primary key,
    automezzo_id                   number
                                   constraint d19_manutenzio_automezzo_i_fk
                                   references d19_automezzo not null,
    descrizione                    varchar2(50 char) not null,
    data_inizio                    date not null,
    data_fine                      date,
    importo                        number
)
;

-- table index
create index d19_manutenzione_i1 on d19_manutenzione (automezzo_id);

-- load data
 
insert into d19_marca (
    id,
    marca
) values (
    1,
    'ALFA'
);

insert into d19_marca (
    id,
    marca
) values (
    2,
    'AUDI'
);

insert into d19_marca (
    id,
    marca
) values (
    3,
    'BMW'
);

insert into d19_marca (
    id,
    marca
) values (
    4,
    'FIAT'
);

insert into d19_marca (
    id,
    marca
) values (
    5,
    'MERCEDES'
);

commit;

alter table d19_marca
modify id generated by default on null as identity restart start with 6;
 
-- load data
-- load data
 
insert into d19_tipo_carburante (
    id,
    tipo_carburante
) values (
    1,
    'BENZINA'
);

insert into d19_tipo_carburante (
    id,
    tipo_carburante
) values (
    2,
    'DIESEL'
);

insert into d19_tipo_carburante (
    id,
    tipo_carburante
) values (
    3,
    'GAS'
);

insert into d19_tipo_carburante (
    id,
    tipo_carburante
) values (
    4,
    'METANO'
);

commit;

alter table d19_tipo_carburante
modify id generated by default on null as identity restart start with 5;
 
 
-- Generated by Quick SQL Sabato Novembre 19, 2022  13:47:19
 
/*
marca /insert 5
  marca /nn /values ALFA, AUDI, BMW, FIAT, MERCEDES /unique

automezzo
  targa vc10 /nn /unique
  marca_id /nn
  modello vc30 /nn

tipo_carburante /insert 4
  tipo_carburante /nn /values BENZINA, DIESEL, GAS, METANO /unique

rifornimento
  automezzo_id /nn
  tipo_carburante_id /nn
  data_rifornimento d /nn
  quantita num /nn
  importo num /nn
 
manutenzione
  automezzo_id /nn
  descrizione vc50 /nn
  data_inizio date /nn
  data_fine  date
  importo num
#ondelete: restrict
#drop: true

# settings = { prefix: "d19",  semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/